/**
 * Generated by tsnapi — public API snapshot of `agent-merge/cli`
 */
// #region Functions
export declare function main(): Promise<void>;
// #endregion

// #region Variables
export declare const cli: Partial<import("@alloc/cmd-ts/dist/cjs/argparser.js").Register> & {
  parse(context: import("@alloc/cmd-ts/dist/cjs/argparser.js").ParseContext): Promise<import("@alloc/cmd-ts/dist/cjs/argparser.js").ParsingResult<{
    command: "submit";
    args: {};
  }>>;
} & import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Named & Partial<import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Descriptive & import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Versioned> & import("@alloc/cmd-ts/dist/cjs/helpdoc.js").PrintHelp & Partial<import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Versioned> & import("@alloc/cmd-ts/dist/cjs/argparser.js").Register & import("@alloc/cmd-ts/dist/cjs/runner.js").Handling<{
  command: "submit";
  args: {};
}, {
  command: "submit";
  value: Promise<void>;
}> & {
  run(context: import("@alloc/cmd-ts/dist/cjs/argparser.js").ParseContext): Promise<import("@alloc/cmd-ts/dist/cjs/argparser.js").ParsingResult<{
    command: "submit";
    value: Promise<void>;
  }>>;
};
export declare const submitCommand: Partial<import("@alloc/cmd-ts/dist/cjs/argparser.js").Register> & {
  parse(context: import("@alloc/cmd-ts/dist/cjs/argparser.js").ParseContext): Promise<import("@alloc/cmd-ts/dist/cjs/argparser.js").ParsingResult<{}>>;
} & import("@alloc/cmd-ts/dist/cjs/helpdoc.js").PrintHelp & import("@alloc/cmd-ts/dist/cjs/helpdoc.js").ProvidesHelp & import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Named & Partial<import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Versioned> & import("@alloc/cmd-ts/dist/cjs/argparser.js").Register & import("@alloc/cmd-ts/dist/cjs/runner.js").Handling<{}, Promise<void>> & {
  run(context: import("@alloc/cmd-ts/dist/cjs/argparser.js").ParseContext): Promise<import("@alloc/cmd-ts/dist/cjs/argparser.js").ParsingResult<Promise<void>>>;
} & Partial<import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Versioned & import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Descriptive & import("@alloc/cmd-ts/dist/cjs/helpdoc.js").Aliased>;
// #endregion