/**
 * Generated by tsnapi — public API snapshot of `agent-merge`
 */
// #region Interfaces
export interface SubmitOptions {
  cwd?: string;
  log?: (_: string) => void;
}
// #endregion

// #region Classes
export declare class AgentMergeError extends Error {
  readonly exitCode: ExitCode;
  constructor(_: string, _?: ExitCode);
}
// #endregion

// #region Functions
export declare function submit(_?: SubmitOptions): Promise<void>;
// #endregion

// #region Variables
export declare const exitCodes: {
  readonly error: 1;
  readonly rebaseConflict: 10;
  readonly verificationFailed: 11;
  readonly worktreeChanged: 12;
  readonly devChanged: 13;
};
// #endregion